// Problems from Project Euler

// #1
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
// Find the sum of all the multiples of 3 or 5 below 1000.
var euler1 = function(number){
    total = 0;
    for (var i = 0; i < number; i++){
        if (i % 3 === 0){
            total += i;
        }
        else if (i % 5 === 0) {
            total += i;
        }
    }
    return total;
};
euler1(1000);


// #2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed 4000000, find the sum of the even-valued terms.
a = 1;
b = 2;
c = 0;
total = 0;
while (a < 4000000) {
    if (a % 2 === 0){
        total += a;
    }
    c = a + b;
    a = b;
    b = c;
}
console.log(total);
